version: "v3.0"
name: 2 blocks test in prod
semaphore_image: standard
blocks:
  - build:
      jobs:
        - name: Job from 1st block
          commands:
            - echo $PPL_ID
            - echo $SEMAPHORE_PIPELINE_ID
  - build:
      jobs:
        - name: Job from 2st block
          commands:
            - echo $PPL_ID
            - "false"
            - echo bar2
  - build:
      jobs:
        - name: Job from 3st block
          commands:
            - echo foo3
            - echo bar3
